#!/usr/bin/env bash
# The following checks if the number of command-line arguments provided is less than 3.
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

# The following checks if the number of command-line arguments provided is greater than or equal to 4.
if [ $# -ge 4 ]; then
    # Transfer the file using scp with strict host key checking disabled and the provided SSH key.
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    # Transfer the file using scp with strict host key checking disabled without providing an explicit SSH key.
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi

