#!/usr/bin/env bash
# configuring web to have an HTTP response header

# Updating packages before installations
sudo apt-get update
sudo apt-get install -y nginx

# creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a moved permanently redirection (301)
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=VE_GH2dJuC4 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to create a custom error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# my custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restart after making custom header
sudo service nginx restart

